<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-UG1IGJU" name="Default test" tests="7" failures="1" timestamp="27 Mar 2017 07:09:12 GMT" time="0.064" errors="0">
  <testcase name="test1" time="0.006" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test4" time="0.009" classname="testNGDemonstration.TestNGTestClass">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.test4() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.test4() didn't finish within the time-out 1
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test2" time="0.001" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test2" time="0.001" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test2" time="0.001" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test2" time="0.001" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test3" time="0.001" classname="testNGDemonstration.TestNGTestClass"/>
</testsuite> <!-- Default test -->
