<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-UG1IGJU" name="testSuit2" tests="7" failures="1" timestamp="27 Mar 2017 07:21:36 GMT" time="0.047" errors="0">
  <testcase name="test1" time="0.001" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test4" time="0.013" classname="testNGDemonstration.TestNGTestClass">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.test4() didn&amp;apos;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.test4() didn't finish within the time-out 1
	at java.lang.Thread.interrupt0(Native Method)
	at java.lang.Thread.interrupt(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 2 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test2" time="0.001" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test2" time="0.001" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test2" time="0.002" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test2" time="0.001" classname="testNGDemonstration.TestNGTestClass"/>
  <testcase name="test3" time="0.001" classname="testNGDemonstration.TestNGTestClass"/>
</testsuite> <!-- testSuit2 -->
