<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-UG1IGJU" name="testNGDemonstration.testNGSuitsAndGroups.TestSuitClass" tests="4" failures="0" timestamp="27 Mar 2017 05:01:28 GMT" time="0.022" errors="1">
  <testcase name="test4" time="0.011" classname="testNGDemonstration.testNGSuitsAndGroups.TestSuitClass">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.test4() didn&#039;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.test4() didn't finish within the time-out 1
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- test4 -->
  <testcase name="test3" time="0.002" classname="testNGDemonstration.testNGSuitsAndGroups.TestSuitClass"/>
  <testcase name="test1" time="0.005" classname="testNGDemonstration.testNGSuitsAndGroups.TestSuitClass"/>
  <testcase name="test2" time="0.004" classname="testNGDemonstration.testNGSuitsAndGroups.TestSuitClass"/>
</testsuite> <!-- testNGDemonstration.testNGSuitsAndGroups.TestSuitClass -->
